### PR TITLE
Revert "Models review"

### PR DESCRIPTION
**Pull request by xiaozhou-liao**
Reverts Book4U-ECSE428/backend#2

### CODE REVIEW

**Comment by xiaozhou-liao** [comment]
How about adding "null=true" for Book's auther and category so that it will be easier to instantiate a new book, i.e. we can seperate the creation of book and that of auther and category.
We are able to set author and category later at any time.

**Comment by billchizhang** [comment]
I think it is better to create book with defined genre and author because I don't think it's a natural expression with add a book and specify its author and genre

**Comment by RushQL** [comment]
@billchizhang   By making the author and genre entity(imagine an author table, and a genre table, independent from the books table) instead of attributes residing in books entity, it is easier to maintain the database and to keep track of them.

**Comment by wzs1234566** [comment]
@billchizhang @RushQL So, do we allow book table have null as author/genre or not?

**Comment by billchizhang** [comment]
@RushQL I got what you mean for the author entity and I agree with you on this. As for its genre, I don't really see why we have to make it an entity. It can just be an attribute of the book class. We can even number-code the genres

**Comment by RushQL** [comment]
@wzs1234566  I vote for yes lol.

**Comment by billchizhang** [comment]
I vote yes for author but no for genre

**Comment by RushQL** [comment]
@billchizhang A book may have many genres. Its a one(one book) to many(many genre) relation, therefore its better to make genre entity. Again think genre as a tag, we want to add tags to a book so ppl can filter books by these tags. （wait its many to many…there are many books）

**Comment by billchizhang** [comment]
@RushQL If we are limiting the genre to one, I think it's better to have book's genre as an attribute. But if there is no limitation, it's better to be an entity. We could have a tag entity but I don't think the genre is a tag from a literature perspective.

**Comment by wzs1234566** [comment]
@billchizhang So it all comes down to your decision, you have 2 things to decide, 1. Books.genre/author many-many entity or attributes? 2. Do we allow null exists in Books table?

**Comment by billchizhang** [comment]
I think first we should allow the author to be an entity with many(many books) to one(author) relation, assuming we are not allowing co-author and genre to be an attribute. But we can add the tag as an entity in sprint 2. As for the second part, I think we should allow null to exist in the book table. Is everyone okay with it?

**Comment by michding** [comment]
@billchizhang I think we were planning to implement an algorithm of recommendation, right?
Based on user's interested book and genre, we can recommend books for them. If we plan to have more feature/relations around genre then we should make it as entity. Otherwise I agree with you, we can just make it as an attribute

**Comment by michding** [comment]
@xiaozhou-liao @billchizhang @RushQL @wzs1234566  
How about a comment or a review, when its user's account got deleted? 
An alternate-> For example: if a user deleted his account, we could keep its comment, and just make the user name as "Book4U user" (I think that's how Facebook does)

**Comment by billchizhang** [comment]
@michding Recommendation is in low priority, we might do it in sprint 3 at best or not at all. Also, if we want to make unique recommendations to each user, we have to keep track of that. We can just simply recommend the highest-rating books to all users

**Comment by billchizhang** [comment]
@michding i think your alternative is good

**Review by billchizhang — APPROVED** [review]

**Comment by michding** [comment]
@billchizhang Our model now states that if a user got removed, then all his comment and review will be deleted as well. That's why I was asking and came up with an alternative. Will see how others think on that

**Comment by billchizhang** [comment]
I mean we could change it or not. It is not a part of our preparation, so I'm okay with either

**Comment by Elsie4ever** [comment]
I agree to make genre as an entity instead of attribute. Because I think a book should have multiple genres. Also, what is the “visibility” attribute in book entity means?

**Review by Elsie4ever — APPROVED** [review]

**Comment by xiaozhou-liao** [comment]
@Elsie4ever For visibility, I currently use it as a flag to indicate the books that are added by user but not yet permitted by a mederator, i.e. a newly added book will not be visible until its approved. Once it's permitted by a moderator, visibility will be set to true.

**Comment by RushQL** [comment]
refer 428database.pdf.

**Pull request closed without merging**
