### PR TITLE
Models review

### PR DESCRIPTION
**Pull request by wzs1234566**
change book.category on_delete to protect
two bigintgerfield changed to intgerfield
new "unknown gender"
vote.user to foreignkey

	new file:   books4u/migrations/0003_auto_20180205_0438.py
	modified:   books4u/models.py

### CODE REVIEW

**Comment by wzs1234566** [comment]
addressing some issues from @xiaozhou-liao and @Chen He.
1. user review books relationship. (in this PR)
2. refactor User to django.contrib.auth's User model (will address this in a new PR)

**Comment by michding** [comment]
Is user.status and user.permission redundant? If a user gets banned, his permission would be downgraded as well. 
If these two are totally different, when a user has higher permission(admin), can another admin change his status?

**Comment by wzs1234566** [comment]
changed books - review and review - vote relationship.

**Comment by wzs1234566** [comment]
@michding user.status and models.STATUS_CHOICE in commit c3f75a7c91d15e90e3fa8f453915e0948a1d9a3b
@billchizhang What would you like this to be? removed or kept?
If removed, moderators are just users with permissions other than "Normal", Users in black list are just users without "Normal" permission.

**Comment by wzs1234566** [comment]
@billchizhang Also, bookCategory and book, many to many or one to many?

**Comment by RushQL** [comment]
@wzs1234566 Book to bookCategory  should be many to many. We want bookcategory acts like tags, so one book can have a tag:computerscience and tag:Guide; or another example, a book can be tag:fiction and tag:sci-fiction.

**Comment by wzs1234566** [comment]
@RushQL Changed to many - many since commit 6daf24b3fbadebf7487efcfcb11a4a3dda29b689

**Pull request merged**
